"""enrollment_methods_and_cohorts

Revision ID: 019df0d81acf
Revises: d7653259d74f
Create Date: 2026-09-07 15:59:56.677008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019df0d81acf'
down_revision = 'd7653259d74f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorts')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('cohort_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_cohort_members_cohort_id_cohorts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cohort_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort_members')),
    sa.UniqueConstraint('cohort_id', 'user_id', name='uq_cohort_members_cohort_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('cohort_syncs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'manager', name='courserole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_cohort_syncs_cohort_id_cohorts')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_cohort_syncs_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort_syncs')),
    sa.UniqueConstraint('course_id', 'cohort_id', name='uq_cohort_syncs_course_cohort'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('course_enrollment_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('self_enrollment_enabled', sa.Boolean(), nullable=False),
    sa.Column('self_enrollment_key', sa.String(length=100), nullable=True),
    sa.Column('guest_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('guest_access_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_enrollment_settings_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_enrollment_settings')),
    sa.UniqueConstraint('course_id', name='uq_course_enrollment_settings_course'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('enrollments', sa.Column('method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'method')
    op.drop_table('course_enrollment_settings')
    op.drop_table('cohort_syncs')
    op.drop_table('cohort_members')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
