"""competencies

Revision ID: 01ec76644b55
Revises: 7594bdb8f280
Create Date: 2026-09-07 23:22:59.301414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ec76644b55'
down_revision = '7594bdb8f280'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'complete', 'waiting_for_review', 'in_review', name='planstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_plans_reviewer_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('competency_frameworks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('idnumber', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scale_id', sa.String(length=36), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_competency_frameworks_created_by_users')),
    sa.ForeignKeyConstraint(['scale_id'], ['scales.id'], name=op.f('fk_competency_frameworks_scale_id_scales')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competency_frameworks')),
    sa.UniqueConstraint('idnumber', name='uq_competency_frameworks_idnumber'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('idnumber', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scale_id', sa.String(length=36), nullable=True),
    sa.Column('proficient_min_rank', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('none', 'all', 'any', name='competencyruletype'), nullable=False),
    sa.Column('rule_outcome', sa.Enum('none', 'evidence', 'complete', name='competencyruleoutcome'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['competency_frameworks.id'], name=op.f('fk_competencies_framework_id_competency_frameworks')),
    sa.ForeignKeyConstraint(['parent_id'], ['competencies.id'], name=op.f('fk_competencies_parent_id_competencies')),
    sa.ForeignKeyConstraint(['scale_id'], ['scales.id'], name=op.f('fk_competencies_scale_id_scales')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competencies')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('course_competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_course_competencies_competency_id_competencies')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_competencies_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_competencies')),
    sa.UniqueConstraint('course_id', 'competency_id', name='uq_course_competencies_course_competency'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('module_competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_module_competencies_competency_id_competencies')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_module_competencies_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_competencies')),
    sa.UniqueConstraint('item_type', 'item_id', 'competency_id', name='uq_module_competencies_item_competency'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('plan_competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_plan_competencies_competency_id_competencies')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_competencies_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_competencies')),
    sa.UniqueConstraint('plan_id', 'competency_id', name='uq_plan_competencies_plan_competency'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('user_competencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('idle', 'waiting_for_review', 'in_review', name='usercompetencystatus'), nullable=False),
    sa.Column('proficiency', sa.Boolean(), nullable=True),
    sa.Column('grade_rank', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_user_competencies_competency_id_competencies')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_user_competencies_reviewer_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_competencies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_competencies')),
    sa.UniqueConstraint('user_id', 'competency_id', name='uq_user_competencies_user_competency'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('user_competency_courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('proficiency', sa.Boolean(), nullable=True),
    sa.Column('grade_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('fk_user_competency_courses_competency_id_competencies')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_user_competency_courses_course_id_courses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_competency_courses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_competency_courses')),
    sa.UniqueConstraint('user_id', 'course_id', 'competency_id', name='uq_user_competency_courses_user_course_competency'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('competency_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_competency_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('log', 'complete', 'override', name='evidenceaction'), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('grade_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_competency_evidence_actor_id_users')),
    sa.ForeignKeyConstraint(['user_competency_id'], ['user_competencies.id'], name=op.f('fk_competency_evidence_user_competency_id_user_competencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competency_evidence')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competency_evidence')
    op.drop_table('user_competency_courses')
    op.drop_table('user_competencies')
    op.drop_table('plan_competencies')
    op.drop_table('module_competencies')
    op.drop_table('course_competencies')
    op.drop_table('competencies')
    op.drop_table('competency_frameworks')
    op.drop_table('plans')
    # ### end Alembic commands ###
