"""wiki_activity

Revision ID: 10319e43eb9d
Revises: 6f39e6c950ba
Create Date: 2026-09-07 15:33:27.094852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10319e43eb9d'
down_revision = '6f39e6c950ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.Enum('collaborative', 'individual', name='wikimode'), nullable=False),
    sa.Column('first_page_title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_wikis_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wikis')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('subwikis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wiki_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_subwikis_owner_id_users')),
    sa.ForeignKeyConstraint(['wiki_id'], ['wikis.id'], name=op.f('fk_subwikis_wiki_id_wikis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subwikis')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('wiki_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subwiki_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('cached_content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_wiki_pages_created_by_users')),
    sa.ForeignKeyConstraint(['subwiki_id'], ['subwikis.id'], name=op.f('fk_wiki_pages_subwiki_id_subwikis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_pages')),
    sa.UniqueConstraint('subwiki_id', 'title', name='uq_wiki_pages_subwiki_title'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('wiki_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_wiki_versions_created_by_users')),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], name=op.f('fk_wiki_versions_page_id_wiki_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_versions')),
    sa.UniqueConstraint('page_id', 'version', name='uq_wiki_versions_page_version'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki_versions')
    op.drop_table('wiki_pages')
    op.drop_table('subwikis')
    op.drop_table('wikis')
    # ### end Alembic commands ###
