"""course_formats

Revision ID: 1e8794533ec6
Revises: 01ec76644b55
Create Date: 2026-09-08 00:11:09.925981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8794533ec6'
down_revision = '01ec76644b55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('format', sa.Enum('topics', 'weeks', 'social', name='courseformat'), nullable=False))
    op.add_column('courses', sa.Column('course_display', sa.Enum('single_page', 'paginated', name='coursedisplay'), nullable=False))
    op.add_column('courses', sa.Column('social_forum_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(op.f('fk_courses_social_forum_id_forums'), 'courses', 'forums', ['social_forum_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_courses_social_forum_id_forums'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'social_forum_id')
    op.drop_column('courses', 'course_display')
    op.drop_column('courses', 'format')
    # ### end Alembic commands ###
