"""conditional_access_and_completion_modes

Revision ID: 2e29f1e9f4ee
Revises: 019df0d81acf
Create Date: 2026-09-07 16:17:17.220514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e29f1e9f4ee'
down_revision = '019df0d81acf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_completion_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.Enum('none', 'manual', 'automatic', name='completionmode'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_completion_configs')),
    sa.UniqueConstraint('item_type', 'item_id', name='uq_activity_completion_configs_item'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('access_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('condition_type', sa.Enum('date', 'grade', 'activity_completion', 'group', name='accessconditiontype'), nullable=False),
    sa.Column('logic', sa.Enum('and_', 'or_', name='accesslogic'), nullable=False),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('grade_item_id', sa.String(length=36), nullable=True),
    sa.Column('min_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('required_item_type', sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'), nullable=True),
    sa.Column('required_item_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['grade_item_id'], ['grade_items.id'], name=op.f('fk_access_conditions_grade_item_id_grade_items')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_access_conditions_group_id_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_conditions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### fin des commandes auto-générées — ajout manuel ci-dessous : Alembic
    # ne détecte pas les changements de valeurs d'un ENUM MySQL existant
    # (même limitation que QuestionType en Épic 1), donc élargissement
    # explicite des 2 colonnes ENUM concernées.
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', name='accessitemtype'),
        existing_nullable=False)


def downgrade() -> None:
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', name='accessitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', name='completionitemtype'),
        existing_nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_conditions')
    op.drop_table('activity_completion_configs')
    # ### end Alembic commands ###
