"""forums_calendar_notifications

Revision ID: 3a145f81dc0c
Revises: 3db75105554d
Create Date: 2026-09-06 11:58:23.081245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a145f81dc0c'
down_revision = '3db75105554d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('new_grade', 'new_forum_post', name='notificationkind'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_calendar_events_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_calendar_events_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('forums',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_forums_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forums')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('forum_discussions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forum_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_forum_discussions_created_by_users')),
    sa.ForeignKeyConstraint(['forum_id'], ['forums.id'], name=op.f('fk_forum_discussions_forum_id_forums')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_discussions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('forum_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('parent_post_id', sa.String(length=36), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_forum_posts_author_id_users')),
    sa.ForeignKeyConstraint(['discussion_id'], ['forum_discussions.id'], name=op.f('fk_forum_posts_discussion_id_forum_discussions')),
    sa.ForeignKeyConstraint(['parent_post_id'], ['forum_posts.id'], name=op.f('fk_forum_posts_parent_post_id_forum_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_posts')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('forum_read_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['forum_discussions.id'], name=op.f('fk_forum_read_state_discussion_id_forum_discussions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_forum_read_state_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_read_state')),
    sa.UniqueConstraint('discussion_id', 'user_id', name='uq_forum_read_state_discussion_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('forum_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['forum_discussions.id'], name=op.f('fk_forum_subscriptions_discussion_id_forum_discussions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_forum_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_subscriptions')),
    sa.UniqueConstraint('discussion_id', 'user_id', name='uq_forum_subscriptions_discussion_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('quizzes', sa.Column('opens_at', sa.DateTime(), nullable=True))
    op.add_column('quizzes', sa.Column('closes_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'closes_at')
    op.drop_column('quizzes', 'opens_at')
    op.drop_table('forum_subscriptions')
    op.drop_table('forum_read_state')
    op.drop_table('forum_posts')
    op.drop_table('forum_discussions')
    op.drop_table('forums')
    op.drop_table('calendar_events')
    op.drop_table('notifications')
    # ### end Alembic commands ###
