"""gradebook

Revision ID: 3db75105554d
Revises: ec501b7e4ef1
Create Date: 2026-09-06 11:21:48.368565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db75105554d'
down_revision = 'ec501b7e4ef1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_grade_categories_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_categories')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('grade_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('grade_category_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.Column('quiz_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('assignment', 'quiz', 'manual', name='gradeitemkind'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('max_points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_grade_items_assignment_id_assignments')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_grade_items_course_id_courses')),
    sa.ForeignKeyConstraint(['grade_category_id'], ['grade_categories.id'], name=op.f('fk_grade_items_grade_category_id_grade_categories')),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_grade_items_quiz_id_quizzes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_items')),
    sa.UniqueConstraint('assignment_id', name=op.f('uq_grade_items_assignment_id')),
    sa.UniqueConstraint('quiz_id', name=op.f('uq_grade_items_quiz_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('manual_grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grade_item_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.String(length=36), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_item_id'], ['grade_items.id'], name=op.f('fk_manual_grades_grade_item_id_grade_items')),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_manual_grades_graded_by_users')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_manual_grades_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_grades')),
    sa.UniqueConstraint('grade_item_id', 'student_id', name='uq_manual_grades_item_student'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_grades')
    op.drop_table('grade_items')
    op.drop_table('grade_categories')
    # ### end Alembic commands ###
