"""live_sessions

Revision ID: 3f7a4d7aaa12
Revises: 715a636dfae2
Create Date: 2026-09-08 03:19:57.578014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7a4d7aaa12'
down_revision = '715a636dfae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('room_name', sa.String(length=64), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('join_window_minutes_before', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_live_sessions_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_sessions')),
    sa.UniqueConstraint('room_name', name=op.f('uq_live_sessions_room_name')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('live_session_attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], name=op.f('fk_live_session_attendance_session_id_live_sessions')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_live_session_attendance_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_session_attendance')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

    # Élargissement manuel de l'ENUM MySQL — non détecté par l'autogenerate,
    # même limitation que les Épics 1/7/9/10/14 : ajout de 'live_session'.
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completion_configs', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'required_item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        existing_nullable=True)
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', 'live_session', name='accessitemtype'),
        existing_nullable=False)


def downgrade() -> None:
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', 'live_session', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', name='accessitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'required_item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        existing_nullable=True)
    op.alter_column('access_conditions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completion_configs', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        existing_nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_session_attendance')
    op.drop_table('live_sessions')
    # ### end Alembic commands ###
