"""workshop_activity

Revision ID: 6a00f392c37c
Revises: 7b1904add2e1
Create Date: 2026-09-07 17:30:21.572833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a00f392c37c'
down_revision = '7b1904add2e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('phase', sa.Enum('setup', 'submission', 'assessment', 'evaluation', 'closed', name='workshopphase'), nullable=False),
    sa.Column('grade', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('gradinggrade', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('strategy', sa.Enum('accumulative', 'comments', 'numerrors', 'rubric', name='workshopstrategy'), nullable=False),
    sa.Column('use_peer_assessment', sa.Boolean(), nullable=False),
    sa.Column('use_self_assessment', sa.Boolean(), nullable=False),
    sa.Column('submission_start', sa.DateTime(), nullable=True),
    sa.Column('submission_end', sa.DateTime(), nullable=True),
    sa.Column('assessment_start', sa.DateTime(), nullable=True),
    sa.Column('assessment_end', sa.DateTime(), nullable=True),
    sa.Column('comparison', sa.Integer(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_workshops_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshops')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('workshop_dimensions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workshop_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('grade', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('label_no', sa.String(length=50), nullable=True),
    sa.Column('label_yes', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('fk_workshop_dimensions_workshop_id_workshops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_dimensions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('workshop_numerrors_map',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workshop_id', sa.String(length=36), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('grade_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('fk_workshop_numerrors_map_workshop_id_workshops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_numerrors_map')),
    sa.UniqueConstraint('workshop_id', 'error_count', name='uq_workshop_numerrors_map_workshop_count'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('workshop_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workshop_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('grade_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback_author', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_workshop_submissions_author_id_users')),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('fk_workshop_submissions_workshop_id_workshops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_submissions')),
    sa.UniqueConstraint('workshop_id', 'author_id', name='uq_workshop_submissions_workshop_author'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('workshop_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('gradinggrade_override', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback_author', sa.Text(), nullable=True),
    sa.Column('feedback_reviewer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_workshop_assessments_reviewer_id_users')),
    sa.ForeignKeyConstraint(['submission_id'], ['workshop_submissions.id'], name=op.f('fk_workshop_assessments_submission_id_workshop_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_assessments')),
    sa.UniqueConstraint('submission_id', 'reviewer_id', name='uq_workshop_assessments_submission_reviewer'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('workshop_rubric_levels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dimension_id', sa.String(length=36), nullable=False),
    sa.Column('grade', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['workshop_dimensions.id'], name=op.f('fk_workshop_rubric_levels_dimension_id_workshop_dimensions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_rubric_levels')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('workshop_grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('dimension_id', sa.String(length=36), nullable=False),
    sa.Column('grade', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('peer_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['workshop_assessments.id'], name=op.f('fk_workshop_grades_assessment_id_workshop_assessments')),
    sa.ForeignKeyConstraint(['dimension_id'], ['workshop_dimensions.id'], name=op.f('fk_workshop_grades_dimension_id_workshop_dimensions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_grades')),
    sa.UniqueConstraint('assessment_id', 'dimension_id', name='uq_workshop_grades_assessment_dimension'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('grade_items', sa.Column('workshop_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(op.f('fk_grade_items_workshop_id_workshops'), 'grade_items', 'workshops', ['workshop_id'], ['id'])
    # ### fin des commandes auto-générées — ajout manuel ci-dessous : Alembic
    # ne détecte pas les changements de valeurs d'un ENUM MySQL existant
    # (même limitation que QuestionType en Épic 1, GradeItemKind en Épic 9).
    op.alter_column('grade_items', 'kind',
        existing_type=sa.Enum('assignment', 'quiz', 'lesson', 'manual', name='gradeitemkind'),
        type_=sa.Enum('assignment', 'quiz', 'lesson', 'manual', 'workshop_submission', 'workshop_grading', name='gradeitemkind'),
        existing_nullable=False)
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completion_configs', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'required_item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        existing_nullable=True)
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', name='accessitemtype'),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', name='accessitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'required_item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        existing_nullable=True)
    op.alter_column('access_conditions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completion_configs', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('grade_items', 'kind',
        existing_type=sa.Enum('assignment', 'quiz', 'lesson', 'manual', 'workshop_submission', 'workshop_grading', name='gradeitemkind'),
        type_=sa.Enum('assignment', 'quiz', 'lesson', 'manual', name='gradeitemkind'),
        existing_nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_grade_items_workshop_id_workshops'), 'grade_items', type_='foreignkey')
    op.drop_column('grade_items', 'workshop_id')
    op.drop_table('workshop_grades')
    op.drop_table('workshop_rubric_levels')
    op.drop_table('workshop_assessments')
    op.drop_table('workshop_submissions')
    op.drop_table('workshop_numerrors_map')
    op.drop_table('workshop_dimensions')
    op.drop_table('workshops')
    # ### end Alembic commands ###
