"""glossary_activity

Revision ID: 6f39e6c950ba
Revises: b3f5bf0439be
Create Date: 2026-09-07 15:02:46.612506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f39e6c950ba'
down_revision = 'b3f5bf0439be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('allow_student_entries', sa.Boolean(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('allow_duplicates', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_glossaries_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossaries')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('glossary_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('glossary_id', sa.String(length=36), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_glossary_entries_created_by_users')),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], name=op.f('fk_glossary_entries_glossary_id_glossaries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_entries')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glossary_entries')
    op.drop_table('glossaries')
    # ### end Alembic commands ###
