"""dashboard_blocks

Revision ID: 715a636dfae2
Revises: 1e8794533ec6
Create Date: 2026-09-08 01:38:44.689972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715a636dfae2'
down_revision = '1e8794533ec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_block_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('block_type', sa.Enum('my_courses', 'calendar', 'recent_activity', 'grades_overview', 'badges', 'messages', 'online_users', 'html', name='blocktype'), nullable=False),
    sa.Column('region', sa.Enum('main', 'side', name='blockregion'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_block_instances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_block_instances')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_table('user_block_instances')
    # ### end Alembic commands ###
