"""badges

Revision ID: 7594bdb8f280
Revises: b3cac4b7cc9b
Create Date: 2026-09-07 21:12:09.788193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7594bdb8f280'
down_revision = 'b3cac4b7cc9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_emoji', sa.String(length=8), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='badgestatus'), nullable=False),
    sa.Column('criteria_logic', sa.Enum('and_', 'or_', name='badgecriterialogic'), nullable=False),
    sa.Column('expire_days', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_badges_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_badges_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('badge_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.Column('criteria_type', sa.Enum('activity', 'course', 'grade', 'cohort', name='badgecriteriatype'), nullable=False),
    sa.Column('logic', sa.Enum('and_', 'or_', name='badgecriterialogic'), nullable=False),
    sa.Column('required_item_type', sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', name='completionitemtype'), nullable=True),
    sa.Column('required_item_id', sa.String(length=36), nullable=True),
    sa.Column('min_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cohort_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], name=op.f('fk_badge_criteria_badge_id_badges')),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_badge_criteria_cohort_id_cohorts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_criteria')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('badge_issued',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('unique_hash', sa.String(length=64), nullable=False),
    sa.Column('awarded_manually', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], name=op.f('fk_badge_issued_badge_id_badges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_badge_issued_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_issued')),
    sa.UniqueConstraint('badge_id', 'user_id', name='uq_badge_issued_badge_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('badge_criteria_met',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('met_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['badge_criteria.id'], name=op.f('fk_badge_criteria_met_criterion_id_badge_criteria')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_badge_criteria_met_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_criteria_met')),
    sa.UniqueConstraint('criterion_id', 'user_id', name='uq_badge_criteria_met_criterion_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge_criteria_met')
    op.drop_table('badge_issued')
    op.drop_table('badge_criteria')
    op.drop_table('badges')
    # ### end Alembic commands ###
