"""lesson_activity

Revision ID: 7b1904add2e1
Revises: 557b2de33d36
Create Date: 2026-09-07 16:55:32.715412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1904add2e1'
down_revision = '557b2de33d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('max_attempts_per_question', sa.Integer(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('allow_retake', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_lessons_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('lesson_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('page_type', sa.Enum('content', 'true_false', 'multiple_choice', 'short_answer', 'numerical', 'essay', name='lessonpagetype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_pages_lesson_id_lessons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_pages')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('lesson_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('answer_text', sa.String(length=1000), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('tolerance', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('jump_type', sa.Enum('next_page', 'previous_page', 'specific_page', 'end_of_lesson', name='lessonjumptype'), nullable=False),
    sa.Column('jump_to_page_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jump_to_page_id'], ['lesson_pages.id'], name=op.f('fk_lesson_answers_jump_to_page_id_lesson_pages')),
    sa.ForeignKeyConstraint(['page_id'], ['lesson_pages.id'], name=op.f('fk_lesson_answers_page_id_lesson_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_answers')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('lesson_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'pending_manual_grading', 'completed', name='lessonattemptstatus'), nullable=False),
    sa.Column('current_page_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_page_id'], ['lesson_pages.id'], name=op.f('fk_lesson_attempts_current_page_id_lesson_pages')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_attempts_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_lesson_attempts_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_attempts')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('lesson_page_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('try_number', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.String(length=36), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.String(length=36), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['lesson_answers.id'], name=op.f('fk_lesson_page_attempts_answer_id_lesson_answers')),
    sa.ForeignKeyConstraint(['attempt_id'], ['lesson_attempts.id'], name=op.f('fk_lesson_page_attempts_attempt_id_lesson_attempts')),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_lesson_page_attempts_graded_by_users')),
    sa.ForeignKeyConstraint(['page_id'], ['lesson_pages.id'], name=op.f('fk_lesson_page_attempts_page_id_lesson_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_page_attempts')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('grade_items', sa.Column('lesson_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(op.f('uq_grade_items_lesson_id'), 'grade_items', ['lesson_id'])
    op.create_foreign_key(op.f('fk_grade_items_lesson_id_lessons'), 'grade_items', 'lessons', ['lesson_id'], ['id'])
    # ### fin des commandes auto-générées — ajout manuel ci-dessous : Alembic
    # ne détecte pas les changements de valeurs d'un ENUM MySQL existant
    # (même limitation que QuestionType en Épic 1 / CompletionItemType en
    # Épic 7), donc élargissement explicite des colonnes ENUM concernées.
    op.alter_column('grade_items', 'kind',
        existing_type=sa.Enum('assignment', 'quiz', 'manual', name='gradeitemkind'),
        type_=sa.Enum('assignment', 'quiz', 'lesson', 'manual', name='gradeitemkind'),
        existing_nullable=False)
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completion_configs', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'required_item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        existing_nullable=True)
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', name='accessitemtype'),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', name='accessitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'required_item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        existing_nullable=True)
    op.alter_column('access_conditions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completion_configs', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('grade_items', 'kind',
        existing_type=sa.Enum('assignment', 'quiz', 'lesson', 'manual', name='gradeitemkind'),
        type_=sa.Enum('assignment', 'quiz', 'manual', name='gradeitemkind'),
        existing_nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_grade_items_lesson_id_lessons'), 'grade_items', type_='foreignkey')
    op.drop_constraint(op.f('uq_grade_items_lesson_id'), 'grade_items', type_='unique')
    op.drop_column('grade_items', 'lesson_id')
    op.drop_table('lesson_page_attempts')
    op.drop_table('lesson_attempts')
    op.drop_table('lesson_answers')
    op.drop_table('lesson_pages')
    op.drop_table('lessons')
    # ### end Alembic commands ###
