"""completion_export_access_log

Revision ID: 8ceb668fd5ba
Revises: 3a145f81dc0c
Create Date: 2026-09-06 12:20:52.754848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ceb668fd5ba'
down_revision = '3a145f81dc0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_completions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.Enum('resource', 'assignment', 'quiz', name='completionitemtype'), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_activity_completions_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_completions')),
    sa.UniqueConstraint('student_id', 'item_type', 'item_id', name='uq_activity_completions_student_item'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('access_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.Enum('course', 'resource', 'assignment', 'quiz', name='accessitemtype'), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_access_logs_course_id_courses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_access_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_logs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_logs')
    op.drop_table('activity_completions')
    # ### end Alembic commands ###
