"""extra_question_types

Revision ID: 99c19d2d84e0
Revises: 68bc6d6e1dc3
Create Date: 2026-09-07 13:56:57.955888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c19d2d84e0'
down_revision = '68bc6d6e1dc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_calculated_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('variable_name', sa.String(length=50), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_calculated_datasets_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_calculated_datasets')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('question_cloze_parts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sub_type', sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', 'numerical', 'calculated', 'multianswer', 'ordering', 'drag_and_drop', name='questiontype'), nullable=False),
    sa.Column('correct_answers', sa.JSON(), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_cloze_parts_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_cloze_parts')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('question_accepted_answers', sa.Column('tolerance', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('questions', sa.Column('calculated_formula', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('calculated_tolerance', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('quiz_responses', sa.Column('resolved_data', sa.JSON(), nullable=True))
    # ### fin des commandes auto-générées — ajout manuel ci-dessous : Alembic
    # ne détecte pas les changements de valeurs d'un ENUM MySQL existant
    # (limitation connue de l'autogenerate), donc élargissement explicite
    # des 2 colonnes ENUM basées sur QuestionType.
    op.alter_column('questions', 'question_type',
        existing_type=sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', name='questiontype'),
        type_=sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', 'numerical', 'calculated', 'multianswer', 'ordering', 'drag_and_drop', name='questiontype'),
        existing_nullable=False)
    op.alter_column('quiz_draw_rules', 'question_type',
        existing_type=sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', name='questiontype'),
        type_=sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', 'numerical', 'calculated', 'multianswer', 'ordering', 'drag_and_drop', name='questiontype'),
        existing_nullable=True)


def downgrade() -> None:
    op.alter_column('quiz_draw_rules', 'question_type',
        existing_type=sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', 'numerical', 'calculated', 'multianswer', 'ordering', 'drag_and_drop', name='questiontype'),
        type_=sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', name='questiontype'),
        existing_nullable=True)
    op.alter_column('questions', 'question_type',
        existing_type=sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', 'numerical', 'calculated', 'multianswer', 'ordering', 'drag_and_drop', name='questiontype'),
        type_=sa.Enum('multiple_choice', 'true_false', 'short_answer', 'essay', 'matching', name='questiontype'),
        existing_nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_responses', 'resolved_data')
    op.drop_column('questions', 'calculated_tolerance')
    op.drop_column('questions', 'calculated_formula')
    op.drop_column('question_accepted_answers', 'tolerance')
    op.drop_table('question_cloze_parts')
    op.drop_table('question_calculated_datasets')
    # ### end Alembic commands ###
