"""private_messaging

Revision ID: b3cac4b7cc9b
Revises: 6a00f392c37c
Create Date: 2026-09-07 20:27:40.475533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3cac4b7cc9b'
down_revision = '6a00f392c37c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('individual', 'group', name='conversationtype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('conv_hash', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('conv_hash', name=op.f('uq_conversations_conv_hash')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('blocked_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], name=op.f('fk_blocked_users_blocked_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blocked_users_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocked_users')),
    sa.UniqueConstraint('user_id', 'blocked_user_id', name='uq_blocked_users_user_blocked'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('contact_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('requested_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_user_id'], ['users.id'], name=op.f('fk_contact_requests_requested_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contact_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_requests')),
    sa.UniqueConstraint('user_id', 'requested_user_id', name='uq_contact_requests_user_requested'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], name=op.f('fk_contacts_contact_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contacts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('user_id', 'contact_id', name='uq_contacts_user_contact'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('conversation_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_members_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_members')),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_members_conversation_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('conversation_user_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('muted', name='conversationactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_user_actions_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_user_actions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_user_actions')),
    sa.UniqueConstraint('conversation_id', 'user_id', 'action', name='uq_conversation_user_actions_conv_user_action'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('message_user_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('read', 'deleted', name='messageactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_user_actions_message_id_messages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_user_actions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_user_actions')),
    sa.UniqueConstraint('message_id', 'user_id', 'action', name='uq_message_user_actions_message_user_action'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('users', sa.Column('message_privacy', sa.Enum('course_member', 'only_contacts', 'site', name='messageprivacy'), nullable=False))
    # ### fin des commandes auto-générées — ajout manuel ci-dessous : Alembic
    # ne détecte pas les changements de valeurs d'un ENUM MySQL existant
    # (même limitation que QuestionType en Épic 1).
    op.alter_column('notifications', 'kind',
        existing_type=sa.Enum('new_grade', 'new_forum_post', name='notificationkind'),
        type_=sa.Enum('new_grade', 'new_forum_post', 'new_message', name='notificationkind'),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column('notifications', 'kind',
        existing_type=sa.Enum('new_grade', 'new_forum_post', 'new_message', name='notificationkind'),
        type_=sa.Enum('new_grade', 'new_forum_post', name='notificationkind'),
        existing_nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'message_privacy')
    op.drop_table('message_user_actions')
    op.drop_table('messages')
    op.drop_table('conversation_user_actions')
    op.drop_table('conversation_members')
    op.drop_table('contacts')
    op.drop_table('contact_requests')
    op.drop_table('blocked_users')
    op.drop_table('conversations')
    # ### end Alembic commands ###
