"""choice_activity

Revision ID: b3f5bf0439be
Revises: 99c19d2d84e0
Create Date: 2026-09-07 14:49:03.749142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f5bf0439be'
down_revision = '99c19d2d84e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple', sa.Boolean(), nullable=False),
    sa.Column('allow_update', sa.Boolean(), nullable=False),
    sa.Column('limit_answers', sa.Boolean(), nullable=False),
    sa.Column('results_display', sa.Enum('never', 'after_answering', 'after_close', 'always', name='choiceresultsdisplay'), nullable=False),
    sa.Column('anonymous_results', sa.Boolean(), nullable=False),
    sa.Column('show_unanswered', sa.Boolean(), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_choices_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_choices')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('choice_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('choice_id', sa.String(length=36), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('max_answers', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], name=op.f('fk_choice_options_choice_id_choices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_choice_options')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('choice_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('choice_id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], name=op.f('fk_choice_answers_choice_id_choices')),
    sa.ForeignKeyConstraint(['option_id'], ['choice_options.id'], name=op.f('fk_choice_answers_option_id_choice_options')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_choice_answers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_choice_answers')),
    sa.UniqueConstraint('choice_id', 'option_id', 'user_id', name='uq_choice_answers_choice_option_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choice_answers')
    op.drop_table('choice_options')
    op.drop_table('choices')
    # ### end Alembic commands ###
