"""scales_and_grade_letters

Revision ID: d31482413e72
Revises: 2e29f1e9f4ee
Create Date: 2026-09-07 16:31:37.213854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31482413e72'
down_revision = '2e29f1e9f4ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_letters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('letter', sa.String(length=10), nullable=False),
    sa.Column('lower_boundary', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_grade_letters_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_letters')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('scales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_scales_course_id_courses')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scales_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scales')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('scale_levels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scale_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scale_id'], ['scales.id'], name=op.f('fk_scale_levels_scale_id_scales')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scale_levels')),
    sa.UniqueConstraint('scale_id', 'rank', name='uq_scale_levels_scale_rank'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('assignments', sa.Column('scale_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(op.f('fk_assignments_scale_id_scales'), 'assignments', 'scales', ['scale_id'], ['id'])
    op.add_column('grade_items', sa.Column('scale_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(op.f('fk_grade_items_scale_id_scales'), 'grade_items', 'scales', ['scale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_grade_items_scale_id_scales'), 'grade_items', type_='foreignkey')
    op.drop_column('grade_items', 'scale_id')
    op.drop_constraint(op.f('fk_assignments_scale_id_scales'), 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'scale_id')
    op.drop_table('scale_levels')
    op.drop_table('scales')
    op.drop_table('grade_letters')
    # ### end Alembic commands ###
