"""groups_and_groupings

Revision ID: d7653259d74f
Revises: 10319e43eb9d
Create Date: 2026-09-07 15:47:33.174279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7653259d74f'
down_revision = '10319e43eb9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_groupings_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groupings')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_groups_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('group_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_members')),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_members_group_user'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('grouping_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grouping_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_grouping_groups_group_id_groups')),
    sa.ForeignKeyConstraint(['grouping_id'], ['groupings.id'], name=op.f('fk_grouping_groups_grouping_id_groupings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grouping_groups')),
    sa.UniqueConstraint('grouping_id', 'group_id', name='uq_grouping_groups_grouping_group'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('choices', sa.Column('group_mode', sa.Enum('no_groups', 'separate_groups', 'visible_groups', name='groupmode'), nullable=False))
    op.add_column('choices', sa.Column('grouping_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(op.f('fk_choices_grouping_id_groupings'), 'choices', 'groupings', ['grouping_id'], ['id'])
    op.add_column('forums', sa.Column('group_mode', sa.Enum('no_groups', 'separate_groups', 'visible_groups', name='groupmode'), nullable=False))
    op.add_column('forums', sa.Column('grouping_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(op.f('fk_forums_grouping_id_groupings'), 'forums', 'groupings', ['grouping_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_forums_grouping_id_groupings'), 'forums', type_='foreignkey')
    op.drop_column('forums', 'grouping_id')
    op.drop_column('forums', 'group_mode')
    op.drop_constraint(op.f('fk_choices_grouping_id_groupings'), 'choices', type_='foreignkey')
    op.drop_column('choices', 'grouping_id')
    op.drop_column('choices', 'group_mode')
    op.drop_table('grouping_groups')
    op.drop_table('group_members')
    op.drop_table('groups')
    op.drop_table('groupings')
    # ### end Alembic commands ###
