"""ecole_nginx_integration

Revision ID: eb92ab858c03
Revises: 8ceb668fd5ba
Create Date: 2026-09-06 13:05:31.849648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb92ab858c03'
down_revision = '8ceb668fd5ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('external_source', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('external_ref_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_courses_external_ref', 'courses', ['external_source', 'external_ref_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_courses_external_ref', 'courses', type_='unique')
    op.drop_column('courses', 'external_ref_id')
    op.drop_column('courses', 'external_source')
    # ### end Alembic commands ###
