"""interactive_videos

Revision ID: f13dda06e44a
Revises: 3acd35aad748
Create Date: 2026-09-08 11:56:26.403115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13dda06e44a'
down_revision = '3acd35aad748'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactive_videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('file', 'url', name='interactivevideosourcetype'), nullable=False),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('stored_path', sa.String(length=1000), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_interactive_videos_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactive_videos')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('interactive_video_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'pending_manual_grading', 'completed', name='interactivevideoattemptstatus'), nullable=False),
    sa.Column('last_position_seconds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_interactive_video_attempts_student_id_users')),
    sa.ForeignKeyConstraint(['video_id'], ['interactive_videos.id'], name=op.f('fk_interactive_video_attempts_video_id_interactive_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactive_video_attempts')),
    sa.UniqueConstraint('video_id', 'student_id', name='uq_interactive_video_attempts_video_student'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('interactive_video_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_seconds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_interactive_video_checkpoints_question_id_questions')),
    sa.ForeignKeyConstraint(['video_id'], ['interactive_videos.id'], name=op.f('fk_interactive_video_checkpoints_video_id_interactive_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactive_video_checkpoints')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('interactive_video_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('answer_data', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.String(length=36), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['interactive_video_attempts.id'], name=op.f('fk_interactive_video_responses_attempt_id_interactive_video_attempts')),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['interactive_video_checkpoints.id'], name=op.f('fk_interactive_video_responses_checkpoint_id_interactive_video_checkpoints')),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name=op.f('fk_interactive_video_responses_graded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactive_video_responses')),
    sa.UniqueConstraint('attempt_id', 'checkpoint_id', name='uq_interactive_video_responses_attempt_checkpoint'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.add_column('grade_items', sa.Column('interactive_video_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(op.f('uq_grade_items_interactive_video_id'), 'grade_items', ['interactive_video_id'])
    op.create_foreign_key(op.f('fk_grade_items_interactive_video_id_interactive_videos'), 'grade_items', 'interactive_videos', ['interactive_video_id'], ['id'])
    # ### end Alembic commands ###

    # Élargissement manuel de l'ENUM MySQL — non détecté par l'autogenerate,
    # même limitation que chaque epic depuis l'Épic 7 : ajout de
    # 'interactive_video'.
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', 'interactive_video', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completion_configs', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', 'interactive_video', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', 'interactive_video', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'required_item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', 'interactive_video', name='completionitemtype'),
        existing_nullable=True)
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', 'live_session', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', 'live_session', 'interactive_video', name='accessitemtype'),
        existing_nullable=False)
    op.alter_column('grade_items', 'kind',
        existing_type=sa.Enum('assignment', 'quiz', 'lesson', 'manual', 'workshop_submission', 'workshop_grading', name='gradeitemkind'),
        type_=sa.Enum('assignment', 'quiz', 'lesson', 'manual', 'workshop_submission', 'workshop_grading', 'interactive_video', name='gradeitemkind'),
        existing_nullable=False)


def downgrade() -> None:
    op.alter_column('grade_items', 'kind',
        existing_type=sa.Enum('assignment', 'quiz', 'lesson', 'manual', 'workshop_submission', 'workshop_grading', 'interactive_video', name='gradeitemkind'),
        type_=sa.Enum('assignment', 'quiz', 'lesson', 'manual', 'workshop_submission', 'workshop_grading', name='gradeitemkind'),
        existing_nullable=False)
    op.alter_column('access_logs', 'item_type',
        existing_type=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', 'live_session', 'interactive_video', name='accessitemtype'),
        type_=sa.Enum('course', 'resource', 'assignment', 'quiz', 'forum', 'lesson', 'workshop', 'live_session', name='accessitemtype'),
        existing_nullable=False)
    op.alter_column('access_conditions', 'required_item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', 'interactive_video', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        existing_nullable=True)
    op.alter_column('access_conditions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', 'interactive_video', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completion_configs', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', 'interactive_video', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        existing_nullable=False)
    op.alter_column('activity_completions', 'item_type',
        existing_type=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', 'interactive_video', name='completionitemtype'),
        type_=sa.Enum('resource', 'assignment', 'quiz', 'forum', 'choice', 'lesson', 'workshop', 'live_session', name='completionitemtype'),
        existing_nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_grade_items_interactive_video_id_interactive_videos'), 'grade_items', type_='foreignkey')
    op.drop_constraint(op.f('uq_grade_items_interactive_video_id'), 'grade_items', type_='unique')
    op.drop_column('grade_items', 'interactive_video_id')
    op.drop_table('interactive_video_responses')
    op.drop_table('interactive_video_checkpoints')
    op.drop_table('interactive_video_attempts')
    op.drop_table('interactive_videos')
    # ### end Alembic commands ###
