export const apps = [
  { slug:'ecoleserv',  name:'ÉcoleServ',   icon:'🏫', version:'1.0.4', category:'Gestion scolaire',     badge:'Populaire', badgeClass:'badge-gold', bg1:'#0d1f2a', bg2:'#0a1a14', desc:"Système complet de gestion d\'établissement scolaire : élèves, paiements, notes, bulletins, présences.", features:['Inscriptions','Paiements par versement','Bulletins PDF','Présences'], tags:['Python','FastAPI','Vue.js','MySQL'] },
  { slug:'infinistock', name:'InfiniStock', icon:'📦', version:'2.1.0', category:'Gestion de stock',     badge:'Nouveau',   badgeClass:'badge-cyan', bg1:'#1a0d2a', bg2:'#0d1a2a', desc:"Gestion d\'inventaire en temps réel avec alertes de stock, codes-barres et rapports.", features:['Inventaire temps réel','Alertes rupture','Code-barres','Rapports'], tags:['Electron','SQLite','React','Node.js'] },
  { slug:'payflow',    name:'PayFlow',      icon:'💳', version:'1.3.2', category:'Finance',              badge:'Stable',    badgeClass:'badge-ok',   bg1:'#0a1f14', bg2:'#14100a', desc:"Solution de gestion des paiements, versements, dettes et rapports financiers.", features:['Versements','Rapports PDF','Multi-devises','Historique'], tags:['Python','FastAPI','Vue.js','PostgreSQL'] },
  { slug:'hrconnect',  name:'HRConnect',   icon:'👥', version:'1.0.1', category:'Ressources humaines',  badge:'Beta',      badgeClass:'badge-cyan', bg1:'#1a1a0a', bg2:'#0a1a1a', desc:"Gestion RH complète : employés, contrats, congés, paie, évaluations.", features:['Employés','Congés','Calcul paie','Évaluations'], tags:['Vue.js','FastAPI','MySQL','Docker'] },
  { slug:'syncbridge', name:'SyncBridge',  icon:'🔄', version:'0.9.5', category:'Infrastructure',       badge:'Beta',      badgeClass:'badge-gold', bg1:'#0d0d1f', bg2:'#1f0d0d', desc:"Synchronisation bidirectionnelle de bases de données entre sites distants.", features:['Sync bidirectionnelle','Conflits','WireGuard','Offline'], tags:['SymmetricDS','MySQL','WireGuard','Python'] },
  { slug:'reportgen',  name:'ReportGen',   icon:'📊', version:'1.2.0', category:'Reporting',            badge:'Stable',    badgeClass:'badge-ok',   bg1:'#1f0a0a', bg2:'#0a1f14', desc:"Générateur de rapports PDF professionnels avec templates personnalisables.", features:['Templates PDF','Export auto','Graphiques','Envois programmés'], tags:['WeasyPrint','Jinja2','Python','FastAPI'] },
]
export const categories = ['Tous', ...new Set(apps.map(a => a.category))]
